services:
  postgres:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - "./nhan_su_cong_ty_phan_mem_150(NhanSu).csv:/tmp/data.csv"
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
